---
codecov:
  notify:
    require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: 50...100
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 90%
ignore:
  # Uses numba
  - src/optimagic/benchmarking/cartis_roberts.py
  - tests/**/*
