#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features="run_py_script",
        source="unit_tests_stderrors.py",
        deps=[ctx.path_to(ctx, "IN_FUNCTIONS", "final_file.py")],
        name="Tests for standard error stuff.",
    )
